import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  AudioWaveform,
  Award,
  Banknote,
  BarChart2,
  Bed,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CreditCard,
  Database,
  FileCheck,
  FileText,
  FlaskConical,
  Gavel,
  Globe,
  Globe2,
  Handshake,
  Hash,
  Headphones,
  HeartPulse,
  HelpCircle,
  Home,
  Image,
  Landmark,
  Layers,
  Linkedin,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Navigation,
  Package,
  PenTool,
  Phone,
  PhoneCall,
  Pill,
  Radio,
  Receipt,
  RotateCcw,
  Scale,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Star,
  Stethoscope,
  Swords,
  Tag,
  Target,
  TrendingUp,
  Truck,
  Trophy,
  Users,
  Video,
  Github,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left-right": ArrowLeftRight,
  "audio-waveform": AudioWaveform,
  award: Award,
  banknote: Banknote,
  "bar-chart-2": BarChart2,
  bed: Bed,
  "book-open": BookOpen,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cloud: Cloud,
  "credit-card": CreditCard,
  database: Database,
  "file-check": FileCheck,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  gavel: Gavel,
  github: Github,
  globe: Globe,
  "globe-2": Globe2,
  handshake: Handshake,
  hash: Hash,
  headphones: Headphones,
  "heart-pulse": HeartPulse,
  home: Home,
  image: Image,
  landmark: Landmark,
  layers: Layers,
  linkedin: Linkedin,
  mail: Mail,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  navigation: Navigation,
  package: Package,
  "pen-tool": PenTool,
  phone: Phone,
  "phone-call": PhoneCall,
  pill: Pill,
  radio: Radio,
  receipt: Receipt,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  search: Search,
  send: Send,
  shield: Shield,
  "shield-check": ShieldCheck,
  ship: Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  star: Star,
  stethoscope: Stethoscope,
  swords: Swords,
  tag: Tag,
  target: Target,
  "trending-up": TrendingUp,
  truck: Truck,
  trophy: Trophy,
  users: Users,
  video: Video,
};

export function getLucideIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? HelpCircle;
}
